ztxz16/fastllm

- cli.py
- include/models/basellm.h
- src/models/chatglm.cpp
- src/models/llama.cpp
- src/models/moss.cpp
如题，已在最新主分支上修复py api中将非unicode字符（如emoji）传给callback导致的退出问题
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: unexpected end of data
> 修复py api中将非unicode字符传给callback导致的退出问题

- tools/fastllm_pytools/torch2flm.py
- tools/scripts/chatglm_export.py
修复ChatGLM模型导出的bug，当不传参数时，由于sys.argv小于2，导致sys.argv[1]会抛出索引序号异常
> 修复ChatGLM模型导出bug

- src/models/chatglm.cpp
- src/models/llama.cpp
- src/models/moss.cpp
在GenerationConfig中将repeat_penalty设置为大于1.0的值时，在WarmUp中进行Forward时会因为lastTokens.units为空导致LLMSampling抛出Segmentation Fault，已修复此问题。
> 修复一个因repeat_penalty大于1导致的segmentation fault错误

- src/model.cpp
- src/models/chatglm.cpp
修复ChatGLMModel构造函数判断版本的逻辑错误，支持使用低内存模式( -l | --low )加载ChatGLM2模型。
测试·：
/main -p ./chatglm2-6b-int4.flm -l
> fix #175 修复ChatGLMModel构造函数判断版本的逻辑错误，支持低内存模式加载ChatGLM2模型

- include/fastllm.h
- src/fastllm.cpp
看起来是ModelLoader的构造函数的buffer参数从std::string_view修改成std::string导致的。
https://github.com/ztxz16/fastllm/commit/530afacc5223d9f1b6007267cef84e0b720314f1
buffer是右值，buffer.data()的指针在buffer对象析构后会失效。
> 修复 USE_MMAP=ON 模型加载过程中发生段错误 #193

- .gitignore
- example/README.md
- example/Win32Demo/Win32Demo.cpp
- example/Win32Demo/Win32Demo.sln
- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
由于Wind32Demo工程代码还是早期版本的，所以增加了fastllm的CPU版本和GPU版本的示例Wisual Studio工程，
目前示例工程不支持编译Python库，需要稍作修改。
> 更新 Win32Demo 以及 Windows 下编译方法

- include/utils/utils.h
- src/devices/cpu/cpudevice.cpp
- src/fastllm.cpp
* 引入`_mm256_set_m128i` 的 intrinsics，修复GCC 7.x上编译报错；（如 #256）
* 更严格地区分AVX2指令集范围，现在可以在仅有AVX而没有AVX2指令集的CPU上编译执行，但目前仅为折衷方案，建议作者修复DotU8U8的AVX版本。
> 支持GCC 7.x编译，以及在没有AVX2的CPU上执行

- tools/fastllm_pytools/llm.py
- tools/src/pytools.cpp
增加stream_response_raw：
* 基于token输入输出（而不是string输入输出）的接口。为了能够更好的控制输入token序列，例如支持像baichuan那样system是先encode到token再拼接的，或其他想要干预token的功能。
* 输出改成使用fetch_response_llm_model。为了更好的支持长尾char被编码为多个token的情况。并绕过了 #326 中提到的内存泄露问题。
顺带增加了tokenizer的接口：
* tokenizer_encode_string：将一个输入字符串进行encode
* tokenizer_decode_token：将单个token 进行decode，没做token序列decode是因为暂时没有直接需要的场景。
tokenizer已经存储在模型中，之前没有暴露给上层，不方便做某些基于token的计算。
现在同时暴露出来，并方便应用方因为其他原因调用。
其他：
看到 `pybinding.cpp`中暴露了 `Tokenizer` 类，但不知道怎么从一个model_id获取它的对象。
> pytools 增加tokenizer接口 与stream_response_raw

- include/models/chatglm.h
- src/models/chatglm.cpp
- tools/fastllm_pytools/torch2flm.py
1. ChatGLM-6B早期发布的版本（[commit 72985e8](https://huggingface.co/THUDM/chatglm-6b/commit/72985e820cb9abb54b924d6152f04db8e8da6b63)之前）vocab_size为150528，且config.jsom中没有gmask_token_id。后更新的slim版本和1.1版本去掉了20000个预留token。本次修改对早期版本做了兼容。
同时根据ChatGLM2的[tokenization_chatglm.py](https://huggingface.co/THUDM/chatglm2-6b/blob/main/tokenization_chatglm.py)，ChatGLM2 的magic number token id 64790和64792的意义分别是gmask_token_id和 bos_token_id。因此做了修改。
2. 修正ChatGLM2-6B的prompt构造问题
在`chatglm-6b` 中，prompt构造在 [ChatGLMForConditionalGeneration.chat()](https://huggingface.co/THUDM/chatglm-6b/blob/main/modeling_chatglm.py#L1267) 方法中，Round的下标从0开始：
```python
if not history:
prompt = query
else:
prompt = ""
for i, (old_query, response) in enumerate(history):
prompt += "[Round {}]\n问：{}\n答：{}\n".format(i, old_query, response) …
```
> 兼容ChatGLM-6B最初版本，并修正ChatGLM2-6B的prompt构造问题

- tools/fastllm_pytools/hf_model.py
transformers>=4.33.0时, model类中会自动包含一个名为active_adapter的方法，但在未加载peft model时调用无效，因此暂时忽略这个方法，仅在其type为string时读取
> 修复transformers>=4.33.0时，activate_adapter作为方法出现在model中的问题

- .gitmodules
修复 @wildkid1024  修改 pyfastllm 时不小心造成的破坏，且将 [pybind/pybind11](https://github.com/pybind/pybind11) 定位到稳定版本 v2.10.5。
> 修复 pybind11 submodule 被破坏导致pyfastllm构建失败

- tools/fastllm_pytools/torch2flm.py
将torch2flm.py中量化权重为4bit时的策略改为非对称量化，以提升4bit模型精度
> 提升torch2flm转换时4bit模型的量化精度

- include/fastllm.h
- include/models/basellm.h
- src/fastllm.cpp
- tools/fastllm_pytools/llm.py
- tools/src/pytools.cpp
增加释放权重所占内存空间的接口：在basellm析构时，自动释放模型权重占用的内存空间；python端也可以手动调用释放接口。
> 增加释放权重所占内存空间的接口

- include/fastllm.h
- src/models/basellm.cpp
- src/models/llama.cpp
- tools/fastllm_pytools/llm.py
- tools/src/pytools.cpp
目标是解决 #360 
改动逻辑：
1. 在GenerationConfig添加了一个stop_token_ids列表，如果有stop tokens可以在创建的时候添加进去，如果不用不影响原来逻辑
2. 在推理时判断是否有符合列表的token id，如果有则认为结束
3. 在python的接口层添加了可选参数stop_token_ids，向下兼容，不影响原有程序，目前很多框架都支持了stop_token_ids参数，兼容性上更好
4. launch_response_str_llm_model和launch_response_llm_model接口有变化，使用的地方都已经改过了
5. 代码已经测试过
> Fixes #360 add stop_token_ids

- example/apiserver/apiserver.cpp
- src/models/glm.cpp
修复GLM模型内存溢出问题。原先GPU推理不会报错，CPU推理时问题才会暴露。问题来自对CatDirect的错误使用。
> 修复GLM模型内存溢出问题

- include/devices/cuda/fastllm-cuda.cuh
- include/fastllm.h
- src/devices/cuda/fastllm-cuda.cu
- src/fastllm.cpp
1. 修复了编译时开启`USE_MMAP`后，在GPU上推理的报错（#303）。不过，使用MMAP后，权重需要先拷贝到内存，再拷贝到GPU，加载很慢，不推荐，
2. 多卡部署下，在多卡之间拷贝时尽可能使用`cudaMemcpyPeer()`方法（#181）。在同一NUMA节点内，qwen-7b 双卡推理速度从单卡的32%左右恢复到80%左右。baichuan-13B从单卡的50%左右恢复到80%左右。
> 两个与ToDevice有关的优化

- README.md
- include/models/chatglm.h
- pyfastllm/README.md
- pyfastllm/examples/cli_low_level.py
- pyfastllm/examples/cli_simple.py
- pyfastllm/fastllm/__init__.py
- pyfastllm/setup.py
- src/pybinding.cpp
1. 修复pyfastllm命令行示例`cli_simple.py`报错和token拼接错误，实现基本功能，应该能支持ChatGLM以外的模型了。
2. 新手反馈pyfastllm编译走不通，或找不到 `cli.py`，故更新文档，
> 修复Pyfastllm的命令行示例并更新文档

- src/devices/cpu/cpudevice.cpp
修复非batch下CPU Attention算子取batch时，由于没有q___bacth导致错误 （#385 ）
也可以采用 #375 中的处理方案。
> 修复非batch下CPU Attention算子取batch错误(#385)

- README.md
- docs/faq.md
- pyfastllm/README.md
- pyfastllm/examples/cli_simple.py
- src/fastllm.cpp
- tools/scripts/cli_demo.py
1. 将线程池修改为懒加载，解决部分Windows环境下加载fastllm模块导致python进程挂起的问题，在Windows 10下，对python绑定API（pyfastllm）和简易python调用（fastllm_pytools），在CPU/GPU测试均正常，修复#232；
2. 增加FAQ文档，重点是提供Windows下编译使用的说明；
3. 修改cli_demo.py，退出时先手动释放显存，( 可参考 #372 )。
> 修复部分系统的挂起问题，支持在Windows下使用Python模块

- src/devices/cuda/fastllm-cuda.cu
- src/fastllm.cpp
- src/models/chatglm.cpp
- tools/fastllm_pytools/hf_model.py
- tools/fastllm_pytools/torch2flm.py
1. 兼容chatglm3-6b-32k 和 chatglm2-6b-32k的位置编码差异，尝试修复 #374 ；
- 目前判断chatglm3逻辑比较简单，GetVersion()版本依然是2，后续如果有了更多chatglm版本，还得继续优化。
3. 修复 `llm.from_hf()` + `model.save()` 模式下，保存的模型中 sentencepiece tokenizer 没有包含score的问题；
见 #397。
4. tokenizer对齐优化，
- 测试发现，transformsers每调用一次 `tokenizer.encode()` 方法，都会在encode的文本前面插入一个空格，因此修改了ChatGLM3中的prompt；
- 实测tokenizer下多个空格并不合并 （#380），暂时注释掉了空格合并逻辑。这块还需进一步跟sentencepiece对齐。
> 兼容chatglm3-6b-32k，修复model.save()保存的模型tokenizer未对齐问题。

- tools/fastllm_pytools/llm.py
#410 具体的报错请见410.
根据410里的建议把tokenizer_encode_string和tokenizer_decode_token都做了修改。避免了在动态线程的时候出现问题。
> 修复输出数据超长，且使用stream_response_raw的时候报错

- README.md
- docs/llama_cookbook.md
- src/models/basellm.cpp
- src/models/llama.cpp
- tools/fastllm_pytools/hf_model.py
- tools/fastllm_pytools/llm.py
- tools/fastllm_pytools/torch2flm.py
- tools/scripts/alpaca2flm.py
1. 修复llama类模型流式输出token卡顿的问题 (#403)；
2. 分别对齐Baichuan-13B-Chat，Baichuan2-13B-Chat模型chat的tokenize结果(#396 #402)，支持两行加速；
3. 增加《LLaMA 类模型转换参考》文档，代码也做了适配。
以上代码基于Baichuan系列测试。
> LLaMA类模型优化

- docs/llama_cookbook.md
- include/fastllm.h
- src/fastllm.cpp
- src/model.cpp
- src/models/llama.cpp
- src/pybinding.cpp
- tools/fastllm_pytools/hf_model.py
- tools/fastllm_pytools/llm.py
- tools/fastllm_pytools/torch2flm.py
- tools/scripts/alpaca2flm.py
- tools/scripts/internlm2flm.py
- tools/src/pytools.cpp
* SentencePiece 
* 支持读取并对齐normalize的设置"add_dummy_prefix"和“remove_extra_whitespaces”，处理前面加一个空格和合并多个空格的情况；
* HuggingFace Tokenizers
* 对齐toeknizer.json格式的BPE Tokenizer，不过由于`PretrainedTokenizerFast`没存储json路径，目前只支持从本地文件转换。
* 支持ByteLevel处理器（将单字节编解码为特殊字符）
* HuggingFace Transformers
* 支持设置特殊token，可在兼容之前flm文件的基础上序列化和反序列化，可使用`set_special_tokens_llm_model`方式在转换时配置，
* 支持 InternLM-7B 模型推理
* 使用的时候最好配置一个`stop_token_id`。
* 测试过Tokenizer的模型：
* XVERSE-7B-chat
* deepseek_coder-1.3b-instruct
* Yi-6B-Chat
> 完全对齐Tokenizer，支持InternLM-7B和XVERSE-7B

- tools/fastllm_pytools/torch2flm.py
修复PR #417 修改后，用torch2flm转换模型时，特殊token字符串的长度错误，导致模型加载失败的问题。
> 修复python脚本转换模型特殊token的错误

- CMakeLists.txt
- example/Android/LLMAssistant/app/src/main/cpp/CMakeLists.txt
- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
- include/models/minicpm.h
- src/model.cpp
- src/models/minicpm.cpp
1. 修复加入MiniCpm模型后，Win32Demo工程编译问题
2.  OpenBMB/MiniCPM#60 中反馈的低内存模式错误，是由于权重引用错误导致的。该问题在GPU初始化时也会出现。
```diff
diff --git a/src/models/minicpm.cpp b/src/models/minicpm.cpp
index 7085b7a..1ee4aa3 100644
--- a/src/models/minicpm.cpp
+++ b/src/models/minicpm.cpp
@@ -241,8 +241,8 @@
{
auto &hiddenStates = *lastHiddenStates;
RMSNorm(hiddenStates, weight["model.norm.weight"], 1e-5, hiddenStates);
Mul(hiddenStates, rms_scale, hiddenStates);
-            Linear(hiddenStates, weight["model.embed_tokens.weight"], Data(), logits);
+            Linear(hiddenStates, weight["lm_head.weight"], Data(), logits);
if (generationConfig.output_logits && retLogits != nullptr) {
int size = logits.dims.back();
logits.ToDevice(DataDevice::CPU);
```
这次作了修复。
3. 将获取缩放因子统一放在initParams()阶段。
> MiniCPM模型Win32Demo工程编译、GPU执行问题修复

- CMakeLists.txt
- docs/faq.md
- src/devices/cuda/fastllm-cuda.cu
fastllm在主分支中增加了fp16算子后，引发了一些编译问题。
1. 在 CUDA < 11.0 以及 CUDA < 11.6 且 Compute Capability < 8.0 时，CUDA 没有定义`__hmax`函数，
3. 老设备（如Tesla M40 / Tesla K40等）不支持fp16计算，因此会编译失败。
本次做了如下的修改：
1. 修复了问题1；
2. 本次更新增加了编译选项`CUDA_NO_TENSOR_CORE`；  
1.  修改了fp16算子部分，开启编译宏后，这部分使用fp32计算；
2.  修改了矩阵乘法的计算方式，优化了 Maxwell、Pascal架构(不包括Tesla P100)，16系列（1660s CMP-40HX ）上的推理速度。
用以下方式测试过：
- cmake 配置`CMAKE_CUDA_ARCHITECTURES`选项，验证编译。
- CentOS 7 CUDA 10.0 CUDA 11.8
- Ubuntu20.04 CUDA 11.0 CUDA 11.3
- Tesla P40 / RTX 1070 测试chatglm/qwen/llama系列。
> 修复NVIDIA旧架构GPU编译问题，初步优化旧架构GPU性能

- src/devices/cuda/fastllm-cuda.cu
1. 针对单条推理decode阶段的GPU GEMV算子优化
a. 在`CUDA_NO_TENSOR_CORE`编译选项下，fp16/int8 修改为向量化访存，获得一定速度提升；
b. 对全部架构int4的GEMV开启向量化访存。
2. 针对int8/int4批量推理的反量化操作
a. 在`CUDA_NO_TENSOR_CORE`编译选项下，修改为向量化访存。
单条推理优化后结果，采用benchmark测试：
|    GPU    | 编译器 | CUDA      |   模型-精度   |  优化前 |  优化后  |
| --------- | ------ | --------- | ------------- | ------- | -------- |
| Tesla P40 | VS2015 | CUDA  9.2 | ChatGLM  fp16 | 20.7tps |  21.4tps |
| Tesla P40 | GCC9.4 | CUDA 10.0 | ChatGLM  fp16 | 20.8tps |  21.5tps |
| Tesla P40 | VS2015 | CUDA  9.2 | ChatGLM2 int8 | 23.6tps |  24.9tps |
| Tesla P40 | GCC9.4 | CUDA 10.0 | ChatGLM2 int8 | 23.6tps |  24.5tps |
| Tesla P40 | VS2015 | CUDA  9.2 | ChatGLM2 int4 | 15.0tps |  **27.6tps** |
| Tesla P40 | GCC9.4 | CUDA 10.0 | ChatGLM2 int4 | 14.8tps |  **27.2tps** |
| GTX1080Ti | GCC8.3 …
> 采用向量化访存优化旧架构GPU性能

- src/devices/cpu/cpudevice.cpp
> 解决，arm64 windows下编译报错

- .github/workflows/Build.yml
- example/Android/LLMAssistant/app/src/main/cpp/CMakeLists.txt
- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
- include/devices/cpu/alivethreadpool.h
- include/fastllm.h
- include/template.h
- include/utils/utils.h
- src/devices/cpu/cpudevice.cpp
- src/model.cpp
- src/models/deepseekv2.cpp
1. 修复 MSVC <cmath> 头文件引入时`M_PI`未定义问题 (#455 之后又有一处有问题，统一修复)；
2. 补充了Windows的`MemoryBarrier()`；
3. POSIX的`sleep()`改用c++11的`std::this_thread::sleep_for()`；
4. POSIX的`access()`改用c++17的`std::filesystem`，为此更新了Andorid NDK版本；
5. Win32Demo 同步了近两个月的修改、
在以下环境编译通过：
* CentOS7 + GCC 8
* Windows 10 + VIsual Studio 2015R3
* Windows 10 + VIsual Studio 2017
> 修复Windows下的编译

- example/apiserver/apiserver.cpp
- example/webui/webui.cpp
- include/utils/utils.h
- main.cpp
- src/model.cpp
1. 修复 #464 中引入的 webui / apiserver 的windows编译问题，修复 main 的 windows编译（只是编译通过）；
2. main / webui / apiserver 找不到文件则退出；
3. webui / apiserver 支持直接读取HF .safetensers 模型；
在以下环境测试过编译：
* Windows 10 + VIsual Studio 2015R3
* CentOS7 + GCC 8.3
在以下环境运行通过：
* CentOS7 + GCC 8.3
> 修复webui/apiserver的Windows编译，并支持直接读取HF模型

- src/devices/cuda/fastllm-cuda.cu
https://blog.csdn.net/qq_42679415/article/details/124265616
> 修复__restrict__导致的restrict is not allowed错误

- example/Win32Demo/Win32Demo.cpp
- example/apiserver/apiserver.cpp
- example/benchmark/benchmark.cpp
- example/webui/webui.cpp
- include/template.h
- main.cpp
- src/model.cpp
- src/models/basellm.cpp
- src/models/llama.cpp
1. 修复直接读取Llama3 HF模型的能力，支持直接读取Qwen2、Qwen1.5的HF模型
2. 配合修改，apiserver webui benchmark使用ChatTemplate
在以下模型上测试通过
- Windows
- Meta-Llama-3-8B-Instruct
- Centos7 
- Meta-Llama-3-8B-Instruct
- Qwen2-1.5B-Instruct（embedding和lm_head权重共享）
- Qwen2-7B-Instruct
- Qwen1.5-1.8B-Chat （需要更新最新的tokenizer_config.json）
- Qwen1.5-7B-Chat （需要更新最新的tokenizer_config.json）
> 直接读取Llama3，Qwen2的HF模型，apiserver webui benchmark使用ChatTemplate

- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
- include/devices/cpu/alivethreadpool.h
- src/fastllm.cpp
- src/model.cpp
- src/models/chatglm.cpp
- src/models/llama.cpp
- tools/fastllm_pytools/hf_model.py
- tools/fastllm_pytools/torch2flm.py
1. 之前，fastllm支持将加载的模型通过`model.save(path)`的方式，保存为flm文件格式。但是支持直接读取.safetensors模型之后，调用`save()`保存的模型再加载会报告各种推理错误，本次对这一问题进行了修复。目前支持GLM4和Qwen1.5/Qwen2
2. 本次修改修复了Windows下加载glm4和qwen2的safetensors时的推理异常。
在以下模型上测试通过
- Windows
- GLM-4-9b-chat
- Qwen2-7B-Instruct
- Qwen1.5-0.5B-Chat
- Centos7 
- GLM-4-9b-chat
- Qwen2-7B-Instruct
- Qwen1.5-0.5B-Chat
> 支持将直接读取safetrensors得到的模型存为flm格式，并加载推理

- example/apiserver/apiserver.cpp
- main.cpp
原因是example/apiserver/apiserver.cpp中自定义的GetCurrentTime函数与VC内置函数重名。
> 修复Windows上MSVC无法成功编译的Bug。

- docs/models.md
- example/Win32Demo/Win32Demo.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
- include/devices/cuda/fastllm-cuda.cuh
- include/template.h
- src/devices/cuda/fastllm-cuda.cu
- src/model.cpp
- src/models/basellm.cpp
- src/template.cpp
修改了Jinja模板的解析，支持布尔变量“true”和“false”，支持[Jinja模板支持"is defined"和“elif”，
现在支持了DeepSeek V2系列模板，因此可以直接读取DeepSeek V2 Lite系列模型。（V2 236B 太大了，没法测试）
* 在以下模型上测试过
deepseek-ai/DeepSeek-V2-Lite-Chat
deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
> C++支持直接加载DeepSeek V2 Lite系列的HF模型

- docs/models.md
- include/template.h
- src/template.cpp
* 根据Jinja模板引擎的文档，支持了“{%-”和“-%}”的去空白语义。
* Jinja模板引擎支持了namespace的创建和参数读取，因此可以支持Deepseek Coder V1的chat_template
在以下模型测试过
* deepseek-ai/Deepseek-Coder-1.3B-Instruct
* deepseek-ai/Deepseek-Coder-6.7B-Instruct
> C++支持直接读取Deepseek Coder V1系列HF模型

- docs/models.md
- example/Win32Demo/Win32Demo.cpp
- example/webui/webui.cpp
- src/models/basellm.cpp
- src/template.cpp
* 修复Jinja模板引擎处理转义字符的错误，忽略模板中工具调用的部分
* Jinja模板引擎支持了not语义以及多个括号，因此可以支持Qwen2.5的chat_template
在以下模型测试过
*  Qwen/Qwen2.5-1.5B-Instruct
*  Qwen/Qwen2.5-Coder-7B-Instruct
> C++支持直接读取Qwen2.5系列HF模型

- docs/models.md
- example/Android/LLMAssistant/app/src/main/cpp/CMakeLists.txt
- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
- include/template.h
- src/model.cpp
- src/models/minicpm3.cpp
- src/models/qwen.cpp
- src/template.cpp
- tools/fastllm_pytools/hf_model.py
- tools/fastllm_pytools/torch2flm.py
- tools/scripts/chatglm_export.py
- tools/scripts/minicpm2flm.py
* 修复 #496 增加Jinja2 `not`运算符之后，导致 Deepseek Coder V1 模板解析异常的问题；
* 支持直接读取Qwen一代模型 `.safetensors` 版本；
* 改进Qwen一代批量推理，改为前向padding，目前batch内部顺序变换输出不一致的问题（#429）显著减少；
* Jinja2模板支持取模运算`%`和数组切片运算符`[:]`，因此支持了 codellama-7b-instruct的HF模型；
* 修改脚本，支持 MiniCPM3-4B 的转换（该模型未提供`.safetensors` 版本）；
* 更新Win32Demo工程以反映项目最新变化；
* 更新文档
在以下模型测试过
* deepseek-ai/Deepseek-Coder-1.3B-Instruct
* openbmb/MiniCPM3-4B
* Qwen/Qwen-1.8b-Chat
* codellama/codellama-7b-instruct
* Qwen/Qwen2.5-Coder-7B-Instruct
* microsoft/Phi-3-mini-4k-instruct
支持 MiniCPM3-4B 和 phi-3.5 的 longRoPE 外推，Qwen2的yarn外推
> C++支持直接读取Qwen一代、codellama系列HF模型，支持转换MiniCPM3

- CMakeLists.txt
- example/Win32Demo/Win32Demo.cpp
- include/fastllm.h
- include/template.h
- src/fastllm.cpp
- src/model.cpp
- src/template.cpp
- test/ops/tokenizerTest.cpp
* 编译
* 尝试将`avx512bf16`指令优化限制在`gcc >= 10.0` `Visual Studio >= 2022`上。
* 增加Tokenizers的单元测试例子`testTokenizer`。使用 `-DUNIT_TEST=ON` 编译`testOps`和`testTokenizer`；
* C++ Tokenizer
* 修复Jinja2模板的多个elseif逻辑；
* Jinja2模板支持字符串`startswith()` `endswith()` `lstrip()` `rstrip()` `strip()`方法；
* Jinja2模板支持切片的逆序操作（如`messages[::-1]`）；
* Jinja2模板支持大于号`>`、小于号`<`；
* 基于以上修改，支持Qwen3的Chat Template；
* 修复#518 Normalize特殊token会加上空白，无法匹配特殊token的问题。
以下模型测试通过
* qwen/Qwen3-1.7B
* microsoft/Phi-3-mini-4k-instruct
* codellama/CodeLlama-7b-Instruct-hf
* deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
* deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
* THUDM/glm-4-9b-chat
> C++支持Qwen3的模板

- tools/fastllm_pytools/openai_server/fastllm_completion.py
- tools/fastllm_pytools/server.py
- tools/fastllm_pytools/util.py
增加了一个dev_mode模式（默认关闭），启用后才可以查看所有对话的ID，并通过API停止对应的对话，有效解决某些第三方平台无法停止对话的情况。（当然只适用于开发环境）
* 获取所有运行的对话
* 停止某一个对话
> 增加主动退出指定对话的方法

- example/Win32Demo/fastllm-gpu.vcxproj
- example/Win32Demo/fastllm-gpu.vcxproj.filters
- example/Win32Demo/fastllm.vcxproj
- example/Win32Demo/fastllm.vcxproj.filters
- include/device.h
- include/devices/cpu/alivethreadpool.h
- include/devices/cpu/cpudevice.h
- src/devices/cpu/avx512vnni.cpp
- src/devices/cpu/cpudevice.cpp
- src/devices/cuda/cudadevice.cpp
- src/devices/cuda/fastllm-cuda.cu
- src/fastllm.cpp
* 修复MSVC编译器报错
* int4g(AWQ)模式下，开启`CUDA_NO_TENSOR_CORE`编译选项，计算能力5.x和6.1的GPU恢复正常prefill速度，
* `--atype float16`模式下，开启`CUDA_NO_TENSOR_CORE`编译选项，计算能力5.x和6.1的GPU恢复正常prefill速度，
* 优化int4g(AWQ)模式下小并发推理的GEMV算子访存连续性，int4g批量推理的反量化操作也修改为向量化访存。
* `--atype float16`模式下，开启`CUDA_NO_TENSOR_CORE`编译选项，Attention计算改为float32模式，对计算能力5.x和6.1的GPU，decode速度有较多提升。<sup>1</sup>
* 修复CopyFrom从大Data到小Data分配失败的问题，解决benchmark报错
* 修复直接内存分配导致float16下int4 prefill速度慢的问题
1. 以前开启`CUDA_NO_TENSOR_CORE`编译选项，新GPU基本也不减速，但是为了加快Attention部分的速度，现在`CUDA_NO_TENSOR_CORE`编译选项下，Attention计算改为float32模式。有较好fp16计算能力的卡（P100，带Tensor Core的GPU）在float16下会减速。
经过测试，新GPU开启`CUDA_NO_TENSOR_CORE`选项后，decode速度下降5%左右，prefill速度下降12%左右。
| GPU       | 编译器 | CUDA      | 模型--精度       | 计算精度 | 场景    | 优化前  | 优化之后    |
| --------- | ------ | --------- | ---------------- …
> 优化GPU在int4g精度下的性能，优化旧GPU在float16计算模式下的性能

- include/devices/cuda/fastllm-cuda.cuh
- include/fastllm.h
- src/devices/cpu/cpudevice.cpp
- src/devices/cuda/cudadevice.cpp
- src/devices/cuda/fastllm-cuda.cu
- src/fastllm.cpp
- src/model.cpp
- src/models/basellm.cpp
- src/models/chatglm.cpp
- src/models/ernie4_5.cpp
- src/models/hunyuan.cpp
* 修改了`NearlyRotatePosition2D`算子的逻辑；
原本该算子是为ChatGLM2系列服务的，`position_id`兼容ChatGLM-6B的特殊格式，同时只处理一半`q`和`k`，提交 d0c22b6 中修改了算子的逻辑，应用在全部`q`和`k`上，适配deepseek_v2，但是chatglm模型没有做对应修改，导致回答混乱；同时deepseek_v2的`position_id`取值位置不准确；本次做了修复。
* 支持Hunyuan的稠密模型系列（Hunyuan-7B-Instruct）；
* 支持ERNIE-4.5-0.3B-PT；
* 修改`Data`释放内存的逻辑；
- `·DUSE_MMAP`选项开启时，无名字的张量需要释放内存
- Fake张量无需释放
* 修改重复惩罚因子（repeat_penalty），当last_n为0时，重复惩罚计算方式与Transfromers一致，但默认不开启。
在以下模型测试过：
* deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct
* paddlepaddle/ERNIE-4.5-0.3B-PT
* tencent/Hunyuan-1.8B-Instruct
* zai-org/chatglm2-6b
> 支持Hunyuan、ERNIE的稠密模型，修复chatglm系列
