main.cpp
=> feat: add history.

main.cpp
=> support reset history.

.gitignore, example/Win32Demo/StringUtils.h, example/Win32Demo/Win32Demo.cpp, example/Win32Demo/Win32Demo.sln, example/Win32Demo/Win32Demo.vcxproj, example/webui/webui.cpp, include/basellm.h, include/chatglm.h, include/factoryllm.h, include/moss.h, src/chatglm.cpp, src/moss.cpp
在windows和Mac上通过IDE和Cmake编译测试没有问题。
=> 调整了代码结构，为异步接收算法返回值添加了回调，添加了Virtual Studio控制台程序示例，添加了其它平台的目录

README.md, web_api.py, web_api_client.py
如题，已从最新分支进行修改，添加了python版web api示例
=> 添加python版web api示例

include/utils/armMath.h
=> Fix typo in armMath.h

pyfastllm/build_libs.py, pyfastllm/demo/cli.py, pyfastllm/demo/web_api.py, pyfastllm/demo/web_api_client.py, src/pybinding.cpp, tools/fastllm_pytools/llm.py, tools/src/pytools.cpp
1. fix py_api, add GenerationConfig, fix pyfastllm/build_libs.py
2. fix fastllm_pytools for windows
=> fix py_api  && fix fastllm_pytools for windows

example/Android/LLMAssistant/.idea/.gitignore, example/Android/LLMAssistant/.idea/.name, example/Android/LLMAssistant/.idea/compiler.xml, example/Android/LLMAssistant/.idea/gradle.xml, example/Android/LLMAssistant/.idea/misc.xml, example/Android/LLMAssistant/.idea/vcs.xml, example/Android/LLMAssistant/app/build.gradle, example/Android/LLMAssistant/app/src/main/java/com/doujiao/xiaozhihuiassistant/MainActivity.java, example/Android/LLMAssistant/app/src/main/java/com/doujiao/xiaozhihuiassistant/utils/UriUtils.java, example/Android/LLMAssistant/app/src/main/res/drawable/editbg.xml, tools/src/pytools.cpp
如题，修复了Android 11+以上版本因存储机制以及MediaStore查询绝对路径机制导致的兼容性问题。
=> fix compatibility issues for Android 11+

include/device.h, include/devices/cpu/cpudevice.h, include/devices/cuda/cudadevice.h, include/devices/cuda/fastllm-cuda.cuh, src/devices/cpu/cpudevice.cpp, src/devices/cuda/cudadevice.cpp, src/devices/cuda/fastllm-cuda.cu, src/executor.cpp
merge之后int8和int4速度下降了非常多.. 先revert回去了
Reverts ztxz16/fastllm#127
=> Revert "add cuda for fp32"

include/devices/cuda/fastllm-cuda.cuh, src/devices/cuda/fastllm-cuda.cu
=> 修改cuda kernel支持多卡

include/fastllm.h, pyfastllm/demo/web_api.py, pyfastllm/demo/web_api_client.py, src/models/chatglm.cpp, src/models/llama.cpp, src/models/moss.cpp, src/pybinding.cpp
如题，修复issue #91 中pyfastllm/demo/web_api.py中并行/api/chat_stream 多线程请求出现的问题，并更新pyfastllm/demo/web_api_client.py。
=> fix problems in issue #91 && update web_api_client.py

tools/scripts/web_demo.py
=> feat: 🎸 optimize web demo

src/models/basellm.cpp
=> 修复basellm中因使用了std::stringstream却没有声明sstream的bug;修复了prompt这个变量声明了两次的bug；

CMakeLists.txt, README.md, include/devices/cpu/cpudevice.h, include/fastllm.h, include/models/qwen.h, src/devices/cpu/cpudevice.cpp, src/fastllm.cpp, src/model.cpp, src/models/qwen.cpp, tools/fastllm_pytools/torch2flm.py, tools/scripts/qwen2flm.py
=> support QWen

tools/fastllm_pytools/hf_model.py
更新了hf_model.py，支持千问7B从huggingface模型导入直接加速
=> 支持千问的两行代码加速

example/Win32Demo/fastllm-gpu.vcxproj, example/Win32Demo/fastllm-gpu.vcxproj.filters, example/Win32Demo/fastllm.vcxproj, example/Win32Demo/fastllm.vcxproj.filters, example/benchmark/benchmark.cpp
包含两个commit: 
1. benchmark Windows版本，加入转码，可正常显示输出，另增加了模型不存在的报错；
2. qwen模型更新后，新增的文件需要加入vs工程中。
=> Win32Demo工程增加Qwen模型

include/fastllm.h, src/fastllm.cpp
Update tiktoken for QWen model, this update shall be able to fix several issues.
=> Update tiktoken for QWen

README.md, tools/fastllm_pytools/torch2flm.py, tools/scripts/baichuan2_2flm.py, tools/scripts/baichuan2flm.py
增加baichuan2转换到fastllm的脚本（baichuan2-7b）
修复baichuan2flm.py中引号配对错误
=> 增加baichuan2转换脚本

src/models/llama.cpp
1. pastKey, pastValue在可能时存储到CUDA上
2. gpu计算logits时先做topk，再将结果传回cpu
=> 更新llama.cpp，应用一些chatglm.cpp中的优化

example/README.md, example/Win32Demo/Win32Demo.cpp, example/Win32Demo/fastllm-gpu.vcxproj, example/Win32Demo/fastllm-gpu.vcxproj.filters, example/Win32Demo/fastllm.vcxproj, example/Win32Demo/fastllm.vcxproj.filters, src/devices/cuda/fastllm-cuda.cu
* 修复了增加GLM模型支持后，Win32Demo工程的编译错误
- 优化了编译说明；
- Win32Demo默认编译支持Pascal / Turing / Ampere架构
* 对主要的CUDA API操作增加错误检测机制，以便详细定位错误。
- 对全部的 `cudaMalloc()` / `cudaFree()` ，主要的`cudaMemcpy()`做了状态判断
- 后续需要完善异常处理逻辑。
=> Win32Demo工程增加GLM模型

tools/fastllm_pytools/llm.py, tools/scripts/setup.py
=> add support macos

CMakeLists.txt, include/models/minicpm.h, src/model.cpp, src/models/minicpm.cpp, tools/fastllm_pytools/hf_model.py
支持 https://github.com/OpenBMB/MiniCPM?tab=readme-ov-file 模型 :
import torch
from transformers import AutoTokenizer, LlamaTokenizerFast, AutoModelForCausalLM
path = 'openbmb/MiniCPM-2B-dpo-fp16'
tokenizer = AutoTokenizer.from_pretrained(path)
model = AutoModelForCausalLM.from_pretrained(path, torch_dtype=torch.float16, device_map='cuda', trust_remote_code=True)
from fastllm_pytools import llm
llm.set_device_map("cpu")
model = llm.from_hf(model, tokenizer, dtype = "float16") # dtype支持 "float16", "int8", "int4"
print(model.response("<用户>山东省最高的山是哪座山, 它比黄山高还是矮？差距多少？<AI>", max_length=256, top_p=0.8,temperature=0.5, repeat_penalty=1.02))
=> support OpenBMB/MiniCPM

src/models/minicpm.cpp
=> fix minicpm

README.md, example/Win32Demo/fastllm.vcxproj, include/models/basellm.h, include/models/minicpm.h, src/models/minicpm.cpp, tools/scripts/minicpm2flm.py
* 修复PR #428 后，Win32Demo CPU版本的编译错误。
* 对齐MiniCPM的tokenizer，简化代码为lLlamaModel类的子类，去掉了 Alibi Mask （本来MiniCPM也没有用Alibi Mask ）。
=> 修复Win32Demo CPU构建错误

include/fastllm.h, src/models/basellm.cpp, src/models/chatglm.cpp
如题，默认为true，不影响目前chatglm的推理逻辑，为false后，将去除chatglm的special token。
请帮忙review，感谢~
=> 添加add_special_tokens选项，默认true，支持chatglm模型

include/fastllm.h, src/models/basellm.cpp, src/models/chatglm.cpp
Reverts ztxz16/fastllm#451
ACTIONS没有过... 先revert了
=> Revert "添加add_special_tokens选项，默认true，支持chatglm模型"

include/fastllm.h, src/models/basellm.cpp, src/models/chatglm.cpp
如题，默认为true，不影响目前chatglm的推理逻辑，为false后，将去除chatglm的special token。
请再帮忙review合入，感谢~
=> 添加add_special_tokens选项，默认true，支持chatglm

tools/fastllm_pytools/hf_model.py, tools/fastllm_pytools/torch2flm.py
考虑到目前直接加载方式尚未完善（如 #465 中的保存操作），支持的模型较少，而传统转换方法还有人使用
因此修改了脚本，支持转换glm-4-9b-chat模型
* THUDM/glm-4-9b-chat
目前测试了2行加速和直接转换，Tokenizer基本对齐
=> 支持转换glm4-9b-chat模型

install.sh
原来make失败会继续运行下去，如果make失败的提示会被刷过去
=> 修改install.sh

README.md, README_EN.md
README中提供的编译指令不够健壮
我的配置：
cmake  3.26.4
cuda  12.2
GPU  NVIDIA A100-PCIE-40GB
在原始编译命令后加入-D CMAKE_CUDA_COMPILER=$(which nvcc)才编译成功
=> modify readme

README.md, README_EN.md, docs/faq.md, include/utils/avxMath.h, src/devices/cuda/fastllm-cuda.cu, src/models/deepseekv2.cpp
* 修复Windows，Linux GCC 7.x、CUDA 9.2等环境下的编译问题
在以下环境编译通过：
* CentOS7 + GCC 8
* Ubuntu 20.04
* Windows 10 + VIsual Studio 2015R3 + CUDA 9.2
* Windows 10 + VIsual Studio 2017 + CUDA 11.6
=> 修复Windows及CUDA 9.2下的编译

include/devices/numa/computeserver.h, src/devices/numa/computeserver.cpp, src/devices/numa/fastllm-numa.cpp
=> 增大/fastllm_shm，保证在8numa的情况下运行deepseek-r1-fp8int8不会内存越界
